const arrCakes = [
    {
    flavor:"",
    priceLarge:"",
    priceMedium:"",
    priceSmall:"",
    imgLarge:"",
    imgMedium:"",
    imgSmall:"",
},
{
    flavor:"",
    priceLarge:"",
    priceMedium:"",
    priceSmall:"",
    imgLarge:"",
    imgMedium:"",
    imgSmall:"",
},
{
    flavor:"",
    priceLarge:"",
    priceMedium:"",
    priceSmall:"",
    imgLarge:"",
    imgMedium:"",
    imgSmall:"",
},
{
    flavor:"",
    priceLarge:"",
    priceMedium:"",
    priceSmall:"",
    imgLarge:"",
    imgMedium:"",
    imgSmall:"",
},
{
    flavor:"",
    priceLarge:"",
    priceMedium:"",
    priceSmall:"",
    imgLarge:"",
    imgMedium:"",
    imgSmall:"",
},
]

export {arrCakes}