const cakeArr = [
  {
    flavor: "Choco Cloud",
    img: "",
    ingredients: ["Cloud cream[heavy cream(milk), whipping cream, sugar]", 
    "Choco cake sheet(liquid egg, sugar, wheat flour, butter, dark cocoa powder, dough improver, baking powder, sea salt)", 
    "Semisweet chocolate", 
    "Strawberry", 
    "Simple syrup (water, sugar, lemon)", 
    "Cocoa powder", 
    "Semisweet chocolate"], 
  },
  {
    flavor: "Mocha Cloud",
    img: "",
    ingredients: ["Mocha cloud cream[heavy cream(milk), coffee extract, whipped cream, sugar]",
    "Mocha cake sheet(liquid egg, sugar, wheat flour, butter, emulsifying agent, coffee extract, baking powder, sea salt)",
    "Strawberry", 
    "Cloud cream[heavy cream(milk), whipped cream, sugar]", 
    "Cake syrup(water, sugar)",
    "Caramel sauce", 
    "Green grape", 
    "Raspberry", 
    "Blueberry", 
    "Glaze"],
  },
  {
    flavor: "Green Tea Cloud",
    img: "",
    ingredients: ["Green tea cake sheet(liquid egg, sugar, wheat flour, butter, green tea powder, emulsifying agent, baking powder, sea salt, food color)", 
    "Cloud cream[heavy cream(milk), whipping cream, sugar]", 
    "Strawberry", 
    "Simple syrup (water, sugar, lemon)", 
    "Green tea sheet crumb", 
    "Blackberry", 
    "Green grape", 
    "Raspberry", 
    "Blueberry", 
    "Glaze"],
  },
  {
    flavor: "Strawberry Cloud",
    img: "",
    ingredients: ["Strawberry cloud cream(heavy cream, whipping cream, sugar, strawberry syrup)", 
    "Strawberry cake sheet[liquid egg, sugar, wheat flour, butter, strawberry syrup, strawberry powder, emulsifying agent, baking powder, sea salt, food coloring(pink)]", 
    "Strawberry", "Simple syrup (water, sugar, lemon)", 
    "Red grape", 
    "Blueberry", 
    "Decorative chocolate", 
    "Glaze"],
  },
  {
    flavor: "",
    img: "",
    ingredients: [],
  },

];
export { cakeArr };
